name: griot_cowrie
description: "This is a chat app that operates in a decentralized manner"
homepage: https://griot.network
repository: https://github.com/griotcowrie/griot_cowrie

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  # Core & Navigation
  flutter:
    sdk: flutter
  go_router: ^18.0.0
  intl: ^0.20.3
  uuid: ^4.6.0

  # State Management & DI
  provider: ^6.1.5+1

  # UI, Assets & Icons
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^11.0.0
  qr_flutter: ^4.1.0
  toastification: ^3.2.0

  # Networking & Web
  http: ^1.6.0
  connectivity_plus: ^7.3.1
  socket_io_client: ^3.1.6
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2

  # Firebase & Notifications
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0

  # Storage & Utilities
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.0.0
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  path: ^1.9.0
  sqflite: ^2.4.1

  # Wallet & Crypto
  wallet: ^0.0.13
  web3dart: ^3.0.3
  bip39_mnemonic: ^4.0.1
  crypto: ^3.0.7
  cryptography: ^2.7.0
  convert: ^3.1.1
  objective_c: ^9.5.0

  # Device Features & Hardware
  local_auth: ^3.0.2
  mobile_scanner: ^7.4.0

  # Media & Images
  cached_network_image: ^4.0.0
  image: ^4.9.1
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  flutter_image_compress: ^2.5.1

  # Monetization & IAP
  google_mobile_ads: ^9.1.0
  in_app_purchase: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/coins_logo/
    - assets/cowrie_images/
    - assets/chains/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/coins_logo/ic_launcher.png"
  adaptive_icon_foreground: "assets/coins_logo/ic_launcher.png"
  adaptive_icon_background: "#00211A"
  min_sdk_android: 21
