// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOe7KI9aigFyB7F7lkBPLAwnymgidrHCY',
    appId: '1:453964227062:android:a9121ba39b91ea1d1d27d7',
    messagingSenderId: '453964227062',
    projectId: 'griot-network',
    storageBucket: 'griot-network.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqsEQUlNmxzZTuaNlputAAPl0JqArirsE',
    appId: '1:453964227062:ios:2f9905bad1942a831d27d7',
    messagingSenderId: '453964227062',
    projectId: 'griot-network',
    storageBucket: 'griot-network.firebasestorage.app',
    iosBundleId: 'com.griotcowrie.griotCowrie',
  );
}
